# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-custom-iptables
  labels:
    app: k8s-custom-iptables
    version: v1
spec:
  selector:
    matchLabels:
      name: k8s-custom-iptables
  template:
    metadata:
      labels:
        name: k8s-custom-iptables
    spec:
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      containers:
        - name: k8s-custom-iptables
          securityContext:
            privileged: true
          image: gcr.io/google_containers/k8s-custom-iptables:1.0
          imagePullPolicy: Always
          command: [ "sh", "-c", "/run.sh" ]
          env:
            - name: SLEEP_INTERVAL
              value: '30'
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
          volumeMounts:
          - mountPath: /cfg
            name: cfg
      volumes:
      - name: cfg
        configMap:
          name: k8s-custom-iptables

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-custom-iptables
data:
  nat.rules: ""
